//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi2_Contatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contato
    {
        public int contato_id { get; set; }
        public int pessoa_id { get; set; }
        public string celular { get; set; }
        public string telefoneResidencial { get; set; }
        public string telefoneComercial { get; set; }
        public string email { get; set; }
        public string IM { get; set; }
        public string sitioweb { get; set; }
        public int tipo { get; set; }
        public string nome_contato { get; set; }
        public Nullable<int> endereco_contato_id { get; set; }
    }
}
