//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi2_Contatos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Endereco
    {
        public int endereco_id { get; set; }
        public int pessoa_id { get; set; }
        public string logradouro { get; set; }
        public string complemento { get; set; }
        public int tipo { get; set; }
        public string estado { get; set; }
        public string cidade { get; set; }
        public string bairro { get; set; }
        public string numero { get; set; }
    }
}
